# This file was generated by GoReleaser. DO NOT EDIT.
cask "asteria-mcp" do
  name "asteria-mcp"
  desc "MCP server for symbolic code search over multiple language servers."
  homepage "https://github.com/n-r-w/asteria"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "asteria-mcp"

  on_macos do
    on_intel do
      url "https://github.com/n-r-w/asteria/releases/download/v#{version}/asteria-#{version}-darwin-amd64.tar.gz"
      sha256 "4162612c204624d4a8c37c0be5cba72529cef1efa13b13273f3314c8e3018a60"
    end
    on_arm do
      url "https://github.com/n-r-w/asteria/releases/download/v#{version}/asteria-#{version}-darwin-arm64.tar.gz"
      sha256 "1bc6de2597e0a08d622cdf2249aa28df2e67f65fd422883158d9e73f881bc861"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/n-r-w/asteria/releases/download/v#{version}/asteria-#{version}-linux-amd64.tar.gz"
      sha256 "022b95589c386873c8e9f6a1306c408bf3a4f3f1ed184f0a137f00f6eaee4cd6"
    end
    on_arm do
      url "https://github.com/n-r-w/asteria/releases/download/v#{version}/asteria-#{version}-linux-arm64.tar.gz"
      sha256 "57400913a0320249e678f7e45267f505ab3995450d0851b41c5330bef9bf5ae3"
    end
  end

  # No zap stanza required
end
