# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ifaceguard < Formula
  desc ""
  homepage ""
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/n-r-w/ifaceguard/releases/download/v1.1.0/ifaceguard_1.1.0_darwin_amd64.tar.gz"
      sha256 "0a07d825d809628e27de382c13f293daab6598f915ebf0121463fa4c7e7b82f9"

      define_method(:install) do
        bin.install "ifaceguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/n-r-w/ifaceguard/releases/download/v1.1.0/ifaceguard_1.1.0_darwin_arm64.tar.gz"
      sha256 "044c258e2c334f59ecb2006adbcb2f5db269fa193b38e99f2e8c595b6eb3add6"

      define_method(:install) do
        bin.install "ifaceguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/n-r-w/ifaceguard/releases/download/v1.1.0/ifaceguard_1.1.0_linux_amd64.tar.gz"
      sha256 "854dde2c93e4448e20869be1dc9c14b0c595ece4d7e92593044e18f24727bdf2"
      define_method(:install) do
        bin.install "ifaceguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n-r-w/ifaceguard/releases/download/v1.1.0/ifaceguard_1.1.0_linux_arm64.tar.gz"
      sha256 "d9ccb50bcd31d9176110c5349552b1ba6cb6f34fe9f94c54f85a4e1d729711d4"
      define_method(:install) do
        bin.install "ifaceguard"
      end
    end
  end
end
