# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ifaceguard < Formula
  desc ""
  homepage ""
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/n-r-w/ifaceguard/releases/download/v0.0.9/ifaceguard_0.0.9_darwin_amd64.tar.gz"
      sha256 "37aa47048dc9ba3114792f562e985982cbe75b10576722735a2e2aa1356601c7"

      def install
        bin.install "ifaceguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/n-r-w/ifaceguard/releases/download/v0.0.9/ifaceguard_0.0.9_darwin_arm64.tar.gz"
      sha256 "96dd26bf7f0fc98a3089bed0d3d87e00b4a91574a7be4461d0548f1f1c1d33bd"

      def install
        bin.install "ifaceguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/n-r-w/ifaceguard/releases/download/v0.0.9/ifaceguard_0.0.9_linux_amd64.tar.gz"
      sha256 "fb7ad6f1eb42c36597a8e13033ba0a204628815b5674381b68b46ede26e659f1"
      def install
        bin.install "ifaceguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n-r-w/ifaceguard/releases/download/v0.0.9/ifaceguard_0.0.9_linux_arm64.tar.gz"
      sha256 "f24ee728b5cfaf9745af71522ecaf8a3d3c75116e02ed53e6ad757c94298269a"
      def install
        bin.install "ifaceguard"
      end
    end
  end
end
