# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeamMcp < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/n-r-w/team-mcp/releases/download/v0.0.3/team-mcp-0.0.3-darwin-amd64.tar.gz"
      sha256 "b5f8dac4ab5ac2211de5fb7ae0338e4c149631575c49bd772e9302c4a4f8f938"

      def install
        bin.install "team-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/n-r-w/team-mcp/releases/download/v0.0.3/team-mcp-0.0.3-darwin-arm64.tar.gz"
      sha256 "66976e6ccac645bb42fdce18542ae07063723cb2810bacb7d7fa1888afb14667"

      def install
        bin.install "team-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/n-r-w/team-mcp/releases/download/v0.0.3/team-mcp-0.0.3-linux-amd64.tar.gz"
      sha256 "9e5a1b2013c9a33f4dd38a516f29a39327f316c7d0e71845cadd600a1dc60302"
      def install
        bin.install "team-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n-r-w/team-mcp/releases/download/v0.0.3/team-mcp-0.0.3-linux-arm64.tar.gz"
      sha256 "77abb91dab1fb6707128c056c39e3fdad3462b33754521fa959c15f3a0b00747"
      def install
        bin.install "team-mcp"
      end
    end
  end
end
