# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeamMcp < Formula
  desc ""
  homepage ""
  version "1.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/n-r-w/team-mcp/releases/download/v1.1.4/team-mcp-1.1.4-darwin-amd64.tar.gz"
      sha256 "bd6392e2cce39904646bbf6b4c9aba8201863c53a687992661492988bffa1ae2"

      def install
        bin.install "team-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/n-r-w/team-mcp/releases/download/v1.1.4/team-mcp-1.1.4-darwin-arm64.tar.gz"
      sha256 "a9d9e62f4c391ff017c7dfae1f2c46b4f97dda140cff4f0dabdb58deeaa0b98b"

      def install
        bin.install "team-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/n-r-w/team-mcp/releases/download/v1.1.4/team-mcp-1.1.4-linux-amd64.tar.gz"
      sha256 "47bded0e381efa5a92195586e47e28af4013c22b131c6fa6d67ffaca65de6cbc"
      def install
        bin.install "team-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n-r-w/team-mcp/releases/download/v1.1.4/team-mcp-1.1.4-linux-arm64.tar.gz"
      sha256 "495ff9b749bc30a54cba5aa2e7e4ebddf6dc5e73abe394d8e7ad0e9d60a33666"
      def install
        bin.install "team-mcp"
      end
    end
  end
end
